apiVersion: v1
kind: ConfigMap
metadata:
  name: seplag-album-config
  namespace: seplag-album
data:
  MINIO_BUCKET: "albuns"
  JWT_EXPIRATION: "300000"
  SPRING_JPA_SHOW_SQL: "false"
  SERVER_PORT: "8080"
