apiVersion: v1
kind: Secret
metadata:
  name: seplag-album-secret
  namespace: seplag-album
type: Opaque
# Valores devem ser codificados em base64
# Exemplo: echo -n 'valor' | base64
data:
  DB_URL: <base64-encoded-jdbc-url>
  DB_USERNAME: <base64-encoded-username>
  DB_PASSWORD: <base64-encoded-password>
  MINIO_URL: <base64-encoded-minio-url>
  MINIO_ACCESS_KEY: <base64-encoded-access-key>
  MINIO_SECRET_KEY: <base64-encoded-secret-key>
  JWT_SECRET: <base64-encoded-jwt-secret>
